development:
  adapter: redis
  url: "redis://localhost:6379/1"
  channel_prefix: the_trivia_game_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: the_trivia_game_production
